version: '3.8'

services:
  # Database Service
  db:
    image: postgres:15-alpine
    container_name: credit_risk_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credit_risk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d credit_risk"]
      interval: 5s
      timeout: 5s
      retries: 5

  # FastAPI Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: credit_risk_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/credit_risk
      - JWT_SECRET=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=10080
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # Mount the local models folder to container so it doesn't need to rebuild image if model changes
      - ./backend/ml_pipeline/models:/app/backend/ml_pipeline/models

  # React Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: credit_risk_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
